---
development:
  cloud_name: dsmbn7dvi
  api_key: '386636476632252'
  api_secret: zfyS2B36qiIT2rtLkGqlxTBvYHU
  enhance_image_tag: true
  static_image_support: false
production:
  cloud_name: dsmbn7dvi
  api_key: '386636476632252'
  api_secret: zfyS2B36qiIT2rtLkGqlxTBvYHU
  enhance_image_tag: true
  static_image_support: true
test:
  cloud_name: dsmbn7dvi
  api_key: '386636476632252'
  api_secret: zfyS2B36qiIT2rtLkGqlxTBvYHU
  enhance_image_tag: true
  static_image_support: false
